accounts/urls.py
from django.urls import path
from . import views

app_name= "user"

urlpatterns = [   
  path('register/',views.signupuser,name="register"),
  path('login/',views.signinuser,name="login"),
  path('logout/',views.logout_user,name="logout"),
  
]

uploadvideo/urls.py
from os import name
from django.urls import path
from . import views

app_name="video"

urlpatterns =[

path('dashboard/',views.dashboard,name="dashboard"),
path('add/',views.videoadd,name="addvideo"),
path('update/<int:id>',views.videoupdate,name="update"),
path('delete/<int:id>',views.deletevideo,name="delete"),
path('embed/',views.embedded,name="embed"),



]

videoApp/urls.py
from django.contrib import admin
from django.urls import path,include
from uploadvideo import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="home"),
    path('user/',include("accounts.urls")),
    path('video/',include("uploadvideo.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

uploadvideo/models.py
from django.db import models
from .validator import file_size
from embed_video.fields import EmbedVideoField

# Create your models here.

class VideoModel(models.Model):

    username = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    caption = models.CharField(max_length=150)
    video = models.FileField(upload_to="video/%y",validators=[file_size])
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.caption
    
    class Meta:
        ordering = ['-created_date']

class EmbedVideo(models.Model):

    title = models.CharField(max_length=150)
    username = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    url = EmbedVideoField()

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        ordering = ["-created_date"]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import fields


class RegisterForm(UserCreationForm):
    
    
    email = forms.EmailField(max_length=150, help_text='Email')


    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2',]


    
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    
  


        

uploadvideo/forms.py
from django import forms
from .models import VideoModel,EmbedVideo

class VideoForm(forms.ModelForm):

    class Meta:
        model = VideoModel

        fields =["caption","video"]
    
class EmbedVideoForm(forms.ModelForm):
    class Meta:

        model = EmbedVideo
        fields=["title","url"]
    

accounts/views.py
from django.contrib.auth.models import User
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from .forms import RegisterForm,LoginForm
from django.contrib import messages


# Create your views here.

def index(request):
    return render(request,"index.html")


def signupuser(request):   
   
    form = RegisterForm(request.POST or None)    
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        
        user = authenticate(username=username, password=password)
        messages.info(request,"you are registered successfully")
        login(request, user)
        return redirect("user:login")
    
    return render(request,'register.html', {'form': form})
   


def signinuser(request):

    form = LoginForm(request.POST or None)
    context = {"form" : form}
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username=username,password=password)

        if user is None:
            messages.info(request,"username or password is wrong")
            return render(request,"loginuser.html",context)
        else:
            messages.success(request,"You are login successfully")
            login(request,user)
            return redirect("video:dashboard")

    return render(request,"loginuser.html",context)

def logout_user(request):
    logout(request)
    messages.info(request,"you are logout")

    return redirect("home")

uploadvideo/views.py
from django.shortcuts import redirect, render,get_object_or_404
from .forms import VideoForm,EmbedVideoForm
from .models import VideoModel,EmbedVideo
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.

def index(request):
    return render(request,"index.html")

@login_required(login_url="user:login")
def videoadd(request):
    form = VideoForm(request.POST, request.FILES )

    if form.is_valid():
        video = form.save(commit=False)
        video.username = request.user
        video.save()

        messages.success(request,"video is added successfully")
        return redirect("video:dashboard")
    return render(request,"videoadd.html",{"form":form})

@login_required(login_url="user:login")
def videoupdate(request,id):
    qr = get_object_or_404(VideoModel,id=id)
    form  =VideoForm(request.POST, request.FILES, instance=qr)

    if form.is_valid():
        newvideo = form.save(commit=False)
        qr.username = request.user

        newvideo.save()
        
        messages.success(request,"video is updated")
        return redirect("video:dashboard")
    return render(request,"update.html",{"form":form})


@login_required(login_url="user:login")
def dashboard(request):
    videos = VideoModel.objects.filter(username = request.user)
    return render(request,"dashboard.html",{"videos":videos})
   

@login_required(login_url="user:login")
def deletevideo(request,id):
    video = get_object_or_404(VideoModel,id=id)

    video.delete()

    messages.success(request,"video is deleted")

    return redirect("video:dashboard")

@login_required(login_url="user:login")
def embedded(request):
    videos = EmbedVideo.objects.filter(username=request.user)
    return render(request,'embed.html',{"videos":videos})

templates/dashboard.html
{% extends "layout.html" %}

{% block content %}




<h3>dashboard</h3>
<p> welcome to the Video App, <h4>{{request.user.username}}</h4></p><hr>
 <div class="container">
  <div class="row">
    <div class="col">
    <th ><a href ="{% url 'video:addvideo' %}" class="btn btn-danger"> video upload</a></th>
    </div>
   
  </div>

  
   <hr><hr>
 

 


<div class="container-fluid pb-video-container">
   {% for vi in videos %}
 <h3 class= "text-center mt-2 mt-2">{{vi.caption}}</h3>
    <div class="col-md-10 col-md-offset-1">
<video width="900" height="500" controls>
  <source src="{{vi.video.url}}" type="video/mp4">
</video>
    <h5>{{vi.created_date}}</h5>         
    <th ><a href ="{% url 'video:update' vi.id %}}" class="btn btn-danger"> update</a></th>
      <th><a href ="{% url 'video:delete' vi.id %}" class="btn btn-danger" >delete</a></th>
           </div>
        
 
 {% endfor %}
  
    
  </div>
 
{% endblock content %}

templates/embed.html
 {% extends "layout.html" %}
 {% load embed_video_tags %}


{% block content %}

<hr><hr>

<div class="container-fluid pb-video-container">

{% for item in videos  %}



<div class="embed-responsive embed-responsive-21by9">

<div class = "px-3 mb-5">

{% video item.url '854x480' %}
<div class="d-flex justify-content-start">  {{item.title}}</div>
</div>

{% endfor %}
</div>
{% endblock content %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" >
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Video Upload</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li> 
        <ul>
        </div>

        <ul class="navbar-nav ml-auto"> 
      
   {% if user.is_authenticated %}

       <li class="nav-item ">
          <a class="nav-link active" href="{% url 'video:embed' %}">Embed Video</a>
        </li>
      <li class="nav-item ">
          <a class="nav-link active" href="{% url 'video:dashboard' %}">Dashboard</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link active" href="{% url 'user:logout' %}">Logout</a>
        </li>
     
   {% else %}                
       
      
        
         

        
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'user:login' %}">Sign in</a>
        </li>

      
          {% endif %} 
        
      
<li class="nav-item">
          <a class="nav-link active" href="{% url 'user:register' %}">Sign up</a>
        </li>
    </ul>
  </div>
</nav>

templates/index.html
{% extends "layout.html" %}

{% block content %}

{% endblock content %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
  {% include "includes/navbar.html" %}
  <div  style= "margin-top:71px" class = "container">
{% if messages %}

    {% for message in messages %}
    {% if message.tags == "info" %}
    <div  class="alert alert-danger">{{ message }} </div>
    {% else %}
    <div  class="alert alert-{{ message.tags }}">{{ message }} </div>
    {% endif %}
    
    {% endfor %}

{% endif %}
  {% block content %}
  
  {% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>  
</body>
</html>

templates/loginuser.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3> login</h3>
<hr>
<form method = "post">
{% csrf_token %}

{{form|crispy}}
<br>
<button type="submit" class="btn btn-danger">login</button>
</form>
  
  </div>
</div>

{% endblock content %}

templates/register.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="col-md-6 offset-md-3">
<h3>sign up</h3>
<hr>
<form method = "post">
{% csrf_token %}

{{form|crispy}}
<br>
<button type="submit" class="btn btn-danger">sign up</button>
</form>
</div>
{% endblock content %}

templates/update.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block content %}



<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3>video update</h3>
<hr>
<form method = "post" enctype="multipart/form-data" >
{% csrf_token %}
{{form.media}}
{{form|crispy}}

<button type="submit" class="btn btn-danger">video update</button>
</form>
  
  </div>
</div>

{% endblock content %}

templates/videoadd.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method = "post" enctype="multipart/form-data" >
{% csrf_token %}
{{form.media}}
{{form|crispy}}

<button type="submit" class="btn btn-danger">add video</button>
</form>
  

{% endblock content %}